services:
  gluetun_pf:
    image: qmcgaw/gluetun:latest
    networks: 
      torrent-networks:
        ipv4_address: 192.168.4.150
    container_name: gluetun_pf
    hostname: gluetun_pf
    environment:
      HTTPPROXY: "on"
      HTTP_CONTROL_SERVER_ADDRESS: ":8000"
      VPN_SERVICE_PROVIDER: custom
      VPN_TYPE: wireguard
      WIREGUARD_ENDPOINT_IP: ${WIREGUARD_ENDPOINT_IP}
      WIREGUARD_ENDPOINT_PORT: 1337
      WIREGUARD_ADDRESSES: ${WIREGUARD_ADDRESSES}
      WIREGUARD_PRIVATE_KEY: ${WIREGUARD_PRIVATE_KEY}
      WIREGUARD_PUBLIC_KEY: ${WIREGUARD_PUBLIC_KEY}
      VPN_PORT_FORWARDING: on
      VPN_PORT_FORWARDING_PROVIDER: "private internet access"
      VPN_PORT_FORWARDING_USERNAME: ${VPN_PORT_FORWARDING_USERNAME}
      VPN_PORT_FORWARDING_PASSWORD: ${VPN_PORT_FORWARDING_PASSWORD}
      SERVER_NAMES: ${SERVER_NAMES}
      HEALTH_SUCCESS_WAIT_DURATION: 180s
      HEALTH_VPN_DURATION_ADDITION: 20s
      FIREWALL_OUTBOUND_SUBNETS: "192.168.4.0/24,192.168.1.0/24"
      VPN_PORT_FORWARDING_STATUS_FILE: "/gluetun/forwarded_port"
      VPN_PORT_FORWARDING_UP_COMMAND: "/bin/sh -c '/usr/bin/wget -O- --retry-connrefused --post-data \"json={\\\"listen_port\\\":{{PORTS}}}\" http://127.0.0.1:8081/api/v2/app/setPreferences 2>&1'"
      TZ: ${TZ}
    ports:
      - target: 8888
        published: "8885"
        protocol: tcp
      - target: 8000
        published: "17888"
        protocol: tcp
      - target: 8080
        published: "10080"
        protocol: tcp
    volumes:
      - type: bind
        source: "${BASEPATH}/${GLUETUN_CONFIG_PATH}"
        target: /gluetun
    restart: on-failure:10
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    labels:
      proxy.aliases: torrent
      proxy.#1.port: 10080
      proxy.#1.homepage: |
        name: "Qbitorrent"
        icon: "@walkxcode/qbittorrent"
        category: "Media"
      
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    network_mode: "service:gluetun_pf"
    container_name: qbittorrent
    environment:
      PGID: ${PGID}
      PUID: "13007"
      TZ: ${TZ}
      UMASK: "002"
      WEBUI_PORT: "8081"
    volumes:
      - type: bind
        source: "${BASEPATH}/${QBITTORRENT_CONFIG_PATH}"
        target: /config
      - type: bind
        source: "${APPLICATION_STORAGE_PATH}/torrents/incomplete"
        target: /data/incomplete
      - type: bind
        source: "${DATA_STORAGE_PATH}/torrents"
        target: /data/torrents
    restart: unless-stopped
    labels:
      proxy.exclude: true

  vuetorrent-backend:
    image: ghcr.io/vuetorrent/vuetorrent-backend:latest
    network_mode: "service:gluetun_pf"
    container_name: vuetorrent-backend
    environment:
      PORT: "8080"
      QBIT_BASE: http://gluetun_pf:8081
      RELEASE_TYPE: stable
      UPDATE_VT_CRON: 0 * * * *
    volumes:
      - type: bind
        source: "${BASEPATH}/${QBITTORRENT_CONFIG_PATH}/bankend-config"
        target: /config
    restart: unless-stopped
    labels:
      proxy.exclude: true

  pyload:
    image: linuxserver/pyload-ng:latest
    network_mode: bridge
    container_name: pyload
    hostname: pyload
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
    ports:
      - target: 8000
        published: "8000"
        protocol: tcp
      - target: 9666
        published: "9666"
        protocol: tcp
    volumes:
      - type: bind
        source: "${BASEPATH}/${PYLOAD_CONFIG_PATH}"
        target: /config
      - type: bind
        source: "${MISC_STORAGE_PATH}/Downloads"
        target: /downloads
    restart: unless-stopped
    labels:
      proxy.aliases: pyload
      proxy.#1.port: 8000
      proxy.idle_timeout: 1h30m

  metube:
    image: ghcr.io/alexta69/metube
    network_mode: bridge
    container_name: metube
    hostname: metube
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
      YTDL_OPTIONS: '{"cookiefile": "/cookies/cookies.txt", "format": "best", "exec": "ffmpeg -i %(filepath)q -c:v libx264 -c:a aac %(filepath)q.h264.mp4"}'
      DELETE_FILE_ON_TRASHCAN: true
    ports:
      - target: 8081
        published: "12081"
        protocol: tcp
    volumes:
      - type: bind
        source: "${BASEPATH}/${METUBE_CONFIG_PATH}/cookies"
        target: /cookies
      - type: bind
        source: "${MISC_STORAGE_PATH}/Downloads"
        target: /downloads
    restart: unless-stopped
    labels:
      proxy.idle_timeout: 30m

  geoip_updater:
    image: crazymax/geoip-updater:latest
    network_mode: bridge
    container_name: geoip_updater
    hostname: geoip_updater
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
    volumes:
      - type: bind
        source: "${BASEPATH}/${RTORRENT_CONFIG_PATH}/geoip"
        target: /data
    env_file:
      - "${BASEPATH}/${RTORRENT_CONFIG_PATH}/geoip-updater.env"
    restart: unless-stopped
    labels:
      proxy.exclude: true

networks:
  torrent-networks:
    name: torrent-networks
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.4.0/24