services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    network_mode: "container:gluetun_pf"
    container_name: qbittorrent
    environment:
      PGID: "13000"
      PUID: "13007"
      TZ: ${TZ}
      UMASK: "002"
      WEBUI_PORT: "8081"
    volumes:
      - type: bind
        source: "${BASEPATH}/${QBITTORRENT_CONFIG_PATH}"
        target: /config
      - type: bind
        source: "${APPLICATION_STORAGE_PATH}/torrents/incomplete"
        target: /data/incomplete
      - type: bind
        source: "${DATA_STORAGE_PATH}/torrents"
        target: /data/torrents
    restart: unless-stopped
    labels:
      proxy.exclude: true
      proxy.depends_on: |
        gluetun_pf: service_healthy

  vuetorrent-backend:
    image: ghcr.io/vuetorrent/vuetorrent-backend:latest
    network_mode: "container:gluetun_pf"
    container_name: vuetorrent-backend
    environment:
      PORT: "8080"
      QBIT_BASE: http://gluetun_pf:8081
      RELEASE_TYPE: stable
      UPDATE_VT_CRON: 0 * * * *
    volumes:
      - type: bind
        source: "${BASEPATH}/${QBITTORRENT_CONFIG_PATH}/bankend-config"
        target: /config
    restart: unless-stopped
    labels:
      proxy.exclude: true
      proxy.depends_on: |
        gluetun_pf: service_healthy

  pyload:
    image: linuxserver/pyload-ng:latest
    network_mode: bridge
    container_name: pyload
    hostname: pyload
    environment:
      PGID: "13000"
      PUID: "1000"
      TZ: ${TZ}
    ports:
      - target: 8000
        published: "8000"
        protocol: tcp
      - target: 9666
        published: "9666"
        protocol: tcp
    volumes:
      - type: bind
        source: "${BASEPATH}/${PYLOAD_CONFIG_PATH}"
        target: /config
      - type: bind
        source: "${DATA_STORAGE_PATH}/Downloads"
        target: /downloads
    restart: unless-stopped

  metube:
    image: ghcr.io/alexta69/metube
    network_mode: bridge
    container_name: metube
    hostname: metube
    environment:
      PGID: "13000"
      PUID: "1000"
      TZ: ${TZ}
      DELETE_FILE_ON_TRASHCAN: true
    ports:
      - target: 8081
        published: "12081"
        protocol: tcp
    volumes:
      - type: bind
        source: "${DATA_STORAGE_PATH}/Downloads"
        target: /downloads
    restart: unless-stopped

  geoip_updater:
    image: crazymax/geoip-updater:latest
    network_mode: bridge
    container_name: geoip_updater
    hostname: geoip_updater
    environment:
      PGID: "13000"
      PUID: "1000"
      TZ: ${TZ}
    volumes:
      - type: bind
        source: "${BASEPATH}/${RTORRENT_CONFIG_PATH}/geoip"
        target: /data
    env_file:
      - "${BASEPATH}/${RTORRENT_CONFIG_PATH}/geoip-updater.env"
    restart: unless-stopped
    labels:
      proxy.exclude: true

  rtorrent_rutorrent:
    image: crazymax/rtorrent-rutorrent:latest
    network_mode: bridge
    container_name: rtorrent_rutorrent
    hostname: rtorrent_rutorrent
    environment:
      PGID: "13000"
      PUID: "13007"
      TZ: ${TZ}
    expose:
      - "${RT_DHT_PORT}/udp"
      - "${XMLRPC_PORT}"
      - "${RUTORRENT_PORT}"
      - "${WEBDAV_PORT}"
      - "${RT_INC_PORT}"
    ports:
      - target: ${RUTORRENT_PORT}
        published: ${RUTORRENT_PORT}
        protocol: tcp
    volumes:
      - type: bind
        source: "${BASEPATH}/${RTORRENT_CONFIG_PATH}"
        target: /data
      - type: bind
        source: "${APPLICATION_STORAGE_PATH}/torrents/incomplete"
        target: /downloads/temp
      - type: bind
        source: "${DATA_STORAGE_PATH}/torrents"
        target: /downloads/complete
      - type: bind
        source: "${BASEPATH}/${RTORRENT_CONFIG_PATH}/passwd"
        target: /passwd
    restart: unless-stopped
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
    labels:
      proxy.aliases: rutorrent


