services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    networks: 
     - torrent-networks:
        ipv4_address: 192.168.4.2
    container_name: qbittorrent
    environment:
      PGID: ${PGID}
      PUID: "13007"
      TZ: ${TZ}
      UMASK: "002"
      WEBUI_PORT: "8080"
    ports:
      - target: 53242
        published: "53242"
        protocol: tcp
      - target: 53242
        published: "53242"
        protocol: udp
    volumes:
      - type: bind
        source: "${BASEPATH}/${QBITTORRENT_CONFIG_PATH}"
        target: /config
      - type: bind
        source: "${APPLICATION_STORAGE_PATH}/torrents/incomplete"
        target: /data/incomplete
      - type: bind
        source: "${DATA_STORAGE_PATH}/torrents"
        target: /data/torrents
    restart: unless-stopped
    labels:
      proxy.exclude: true

  vuetorrent-backend:
    image: ghcr.io/vuetorrent/vuetorrent-backend:latest
    networks: 
     - torrent-networks:
        ipv4_address: 192.168.4.3
    container_name: vuetorrent-backend
    environment:
      PORT: "8080"
      QBIT_BASE: http://qbittorrent:8080
      RELEASE_TYPE: stable
      UPDATE_VT_CRON: 0 * * * *
    ports:
      - target: 8080
        published: "10080"
        protocol: tcp
    volumes:
      - type: bind
        source: "${BASEPATH}/${QBITTORRENT_CONFIG_PATH}/bankend-config"
        target: /config
    restart: unless-stopped
    labels:
      proxy.aliases: torrent
      proxy.#1.port: 10080
      proxy.#1.middlewares.forwardauth.bypass: path /v1/* | path /api/*

  pyload:
    image: linuxserver/pyload-ng:latest
    network_mode: bridge
    container_name: pyload
    hostname: pyload
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
    ports:
      - target: 8000
        published: "8000"
        protocol: tcp
      - target: 9666
        published: "9666"
        protocol: tcp
    volumes:
      - type: bind
        source: "${BASEPATH}/${PYLOAD_CONFIG_PATH}"
        target: /config
      - type: bind
        source: "${MISC_STORAGE_PATH}/Downloads"
        target: /downloads
    restart: unless-stopped
    labels:
      proxy.aliases: pyload
      proxy.#1.port: 8000
      proxy.idle_timeout: 1h30m

  metube:
    image: ghcr.io/alexta69/metube
    network_mode: bridge
    container_name: metube
    hostname: metube
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
      YTDL_OPTIONS: '{"cookiefile": "/cookies/cookies.txt", "format": "best", "exec": "ffmpeg -i %(filepath)q -c:v libx264 -c:a aac %(filepath)q.h264.mp4"}'
      DELETE_FILE_ON_TRASHCAN: true
    ports:
      - target: 8081
        published: "12081"
        protocol: tcp
    volumes:
      - type: bind
        source: "${BASEPATH}/${METUBE_CONFIG_PATH}/cookies"
        target: /cookies
      - type: bind
        source: "${MISC_STORAGE_PATH}/Downloads"
        target: /downloads
    restart: unless-stopped
    labels:
      proxy.idle_timeout: 30m
      
  geoip_updater:
    image: crazymax/geoip-updater:latest
    network_mode: bridge
    container_name: geoip_updater
    hostname: geoip_updater
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
    volumes:
      - type: bind
        source: "${BASEPATH}/${RTORRENT_CONFIG_PATH}/geoip"
        target: /data
    env_file:
      - "${BASEPATH}/${RTORRENT_CONFIG_PATH}/geoip-updater.env"
    restart: unless-stopped
    labels:
      proxy.exclude: true

networks:
  torrent-networks:
    name: torrent-networks
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.4.0/24