services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    network_mode: bridge
    container_name: jellyfin
    hostname: jellyfin
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
      UMASK: "002"
    ports:
      - target: 8096
        published: "8096"
        protocol: tcp
    volumes:
      - type: bind
        source: "${BASEPATH}/${JELLYFIN_CONFIG_PATH}"
        target: /config
      - type: bind
        source: "${INFUSE_MEDIA_STORAGE_PATH}"
        target: /data
      - type: bind
        source: "${MISC_STORAGE_PATH}/Downloads"
        target: /pyload-downloads
    restart: unless-stopped
    labels:
      proxy.#1.middlewares.forward_auth.bypass: path /*
      proxy.idle_timeout: 45m

  ombi:
    image: lscr.io/linuxserver/ombi:latest
    network_mode: bridge
    container_name: ombi
    hostname: ombi
    environment:
      PGID: ${PGID}
      PUID: "13009"
      TZ: ${TZ}
      UMASK: "002"
    ports:
      - target: 3579
        published: "3579"
        protocol: tcp
    volumes:
      - type: bind
        source: "${BASEPATH}/${OMBI_CONFIG_PATH}"
        target: /config
    restart: unless-stopped
    labels:
      proxy.idle_timeout: 45m
      proxy.depends_on: |
        - jellyfin:service_started

  plex:
    image: plexinc/pms-docker:plexpass
    network_mode: bridge
    container_name: plex
    hostname: plex
    environment:
      ADVERTISE_IP: "http://${LOCALHOST}:32400"
      PGID: ${PGID}
      PLEX_CLAIM: ${PLEX_CLAIM}
      PUID: "13010"
      TZ: ${TZ}
      UMASK: "002"
    ports:
      - target: 32400
        published: "32400"
        protocol: tcp
      - target: 8324
        published: "8324"
        protocol: tcp
      - target: 32469
        published: "32469"
        protocol: tcp
      - target: 1900
        published: "1900"
        protocol: udp
      - target: 32410
        published: "32410"
        protocol: udp
      - target: 32412
        published: "32412"
        protocol: udp
      - target: 32413
        published: "32413"
        protocol: udp
      - target: 32414
        published: "32414"
        protocol: udp
    volumes:
      - type: bind
        source: "${BASEPATH}/${PLEX_CONFIG_PATH}"
        target: /config
      - type: bind
        source: "${BASEPATH}/${PLEX_CONFIG_PATH}/transcode"
        target: /transcode
      - type: bind
        source: "${MISC_STORAGE_PATH}/Downloads"
        target: /pyload-downloads
      - type: bind
        source: "${INFUSE_MEDIA_STORAGE_PATH}"
        target: /data
    restart: unless-stopped
    labels:
      proxy.aliases: plex, plex.picityvietnam.com
      proxy.idle_timeout: 45m
      proxy.#1.middlewares.forwardauth.bypass:
      proxy.#1.port: 32400
      proxy.#2.port: 32400
      proxy.#2.middlewares.forwardauth.bypass:

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    network_mode: bridge
    container_name: tautulli
    hostname: tautulli
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
      UMASK: "002"
    ports:
      - target: 8181
        published: "8181"
        protocol: tcp
    volumes:
      - type: bind
        source: "${BASEPATH}/${TAUTULLI_CONFIG_PATH}"
        target: /config
    restart: unless-stopped
    labels:
      proxy.idle_timeout: 45m
      proxy.depends_on: |
        - plex:service_started


