[[stack]]
name = "database"
tags = ["data"]
[stack.config]
server = "HomeLab"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
linked_repo = "Komodo-Github"
run_directory = "stacks/Database"
file_paths = [
  "mariadb.yaml",
  "mongodb.yaml",
  "mysql.yaml",
  "postgres.yaml",
  "redis.yaml"
]
env_file_path = "database.env"
additional_env_files = ["../../MainSystem/.env"]
environment = """
MONGO_INITDB_ROOT_PASSWORD=mongodb
MONGO_INITDB_ROOT_USERNAME=mongodb
MONGODB_CONFIG_PATH=mongodb-config
MYSQL_ROOT_PASSWORD=mysql
MYSQL_CONFIG_PATH=mysql-config
MARIADB_ROOT_PASSWORD=mariadb
MARIADB_CONFIG_PATH=mariadb-config
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
POSTGRES_CONFIG_PATH=postgresql-config
"""

##

[[stack]]
name = "syncing-center"
tags = ["data"]
[stack.config]
server = "HomeLab"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
linked_repo = "Komodo-Github"
run_directory = "stacks/Syncing"
additional_env_files = ["../../MainSystem/.env"]
environment = """
ALIST_CONFIG_PATH=alist-config
RClONE_CONFIG_PATH=rclone-config
INFUSE_MEDIA_STORAGE_PATH=/mnt/Data/Infuse/media
APPLICATION_STORAGE_PATH=/mnt/Application/Downloads
MISC_STORAGE_PATH=/mnt/Storage
"""

##

[[stack]]
name = "vaultwarden"
tags = ["tools", "data"]
[stack.config]
server = "HomeLab"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
linked_repo = "Komodo-Github"
run_directory = "stacks/Vaultwarden"
additional_env_files = ["../../MainSystem/.env"]
environment = """
APP_CONFIG_PATH=vaultwarden-config
"""