services:
  gost:
    image: "gogost/gost:latest"
    container_name: gost-client
    hostname: gost-client
    environment:
      TZ: ${TZ}
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    command: -L rtcp://:8890/192.168.1.3:8890 -F relay://user:pass123@1.2.3.4:8445
    labels:
      proxy.exclude: true