services:
  gost:
    image: "gogost/gost:latest"
    container_name: gost-client
    hostname: gost-client
    environment:
      TZ: ${TZ}
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    command: -L rtcp://:8890/192.168.1.3:8890 -F relay://tunnel:8bf87c19b6a2a32492a0a65a5f795219936355bb@38.54.17.235:12446
    labels:
      proxy.exclude: true