services:
  gost:
    image: "gogost/gost:latest"
    container_name: gost-server
    hostname: gost-server
    environment:
      TZ: ${TZ}
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    network_mode: host
    command: -L relay://user_v3:pass_v34@0.0.0.0:8445?bind=true
    labels:
      proxy.exclude: true