################################
# 🦎 KOMODO COMPOSE - MONGO 🦎 #
################################

## This compose file will deploy:
## Komodo Core
## KOMODO PERIPHERY has been installed by systemd script at https://github.com/moghtech/komodo/tree/main/scripts
##

services:
  core:
    image: ghcr.io/moghtech/komodo-core:latest
    hostname: komodo
    container_name: komodo
    restart: unless-stopped
    ports:
      - target: "9120"
        published: "9122"
        protocol: tcp
    environment:
      KOMODO_DATABASE_ADDRESS: "${LOCALHOST}:27017"
      KOMODO_DATABASE_USERNAME: "${KOMODO_DATABASE_USERNAME:-mongodb}"
      KOMODO_DATABASE_PASSWORD: "${KOMODO_DATABASE_PASSWORD:-mongodb}"
      TZ: Asia/Ho_Chi_Minh
    network_mode: bridge
    volumes:
      ## Store dated backups of the database - https://komo.do/docs/setup/backup
      - /etc/komodo/backups:/backups
      ## Store sync files on server
      - /etc/komodo/syncs:/syncs
    ## Allows for systemd Periphery connection at
    ## "https://host.docker.internal:8120"
    extra_hosts:
      - host.docker.internal:host-gateway
    labels:
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers
      proxy.aliases: komodo # For godoxy