services:
  mysql:
    image: mysql:8.4
    network_mode: bridge
    container_name: mysql
    hostname: mysql
    environment:
      MYSQL_DATABASE: sample
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-mysql}
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
      UMASK: "002"
    ports:
      - ${MYSQL_PORT:-3306}:3306
    volumes:
      - type: bind
        source: "${BASEPATH}/${MYSQL_CONFIG_PATH}/data"
        target: /var/lib/mysql
    command: --mysql-native-password=ON
    restart: unless-stopped