services:
  redis:
    image: redis:latest
    network_mode: bridge
    container_name: redis
    hostname: redis
    ports:
      - ${REDIS_PORT:-6379}:6379
    command:
      - redis-server
      - --save
      - ""
      - --maxmemory
      - 128mb
      - --maxmemory-policy
      - allkeys-lru
    restart: unless-stopped