networks:
  torrent-networks:
    external: true
services:
  gost:
    image: "gogost/gost:latest"
    container_name: gost
    hostname: gost
    environment:
      TZ: ${TZ}
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    networks:
      torrent-networks:
        ipv4_address: 192.168.4.100
    command: ${GOST_CLIENT_CMD}
    labels:
      proxy.exclude: true