networks:
  vpn:
    name: proxy_vpn
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.3.0/24

services:
  gost:
    image: "gogost/gost:latest"
    container_name: gost
    hostname: gost
    environment:
      TZ: ${TZ}
    ports:
      - target: 30000
        published: "30000"
        protocol: tcp
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    networks:
      vpn:
        ipv4_address: 192.168.3.99
    command: "-L :30000 -F ss://chacha20-ietf-poly1305:password@192.168.3.100:8388"

  gluetun_pf:
    image: qmcgaw/gluetun:latest
    networks:
      vpn:
        ipv4_address: 192.168.3.150
    container_name: gluetun_pf
    hostname: gluetun_pf
    environment:
      HTTP_CONTROL_SERVER_ADDRESS: ":8000"
      VPN_SERVICE_PROVIDER: custom
      VPN_TYPE: wireguard
      WIREGUARD_ENDPOINT_IP: 173.239.247.173
      WIREGUARD_ENDPOINT_PORT: 1337
      WIREGUARD_ADDRESSES: 10.19.219.243
      WIREGUARD_PRIVATE_KEY: yH0cgQlWswV89MOya9MlTwf+x86znoF2Ui3kfA5Mcmc=
      WIREGUARD_PUBLIC_KEY: tJ9qYDVzAei15fYzzkdoWQvyajNZeE3I7ViBMOH2kE4=
      VPN_PORT_FORWARDING: on
      VPN_PORT_FORWARDING_PROVIDER: "private internet access"
      VPN_PORT_FORWARDING_USERNAME: "p8001972"
      VPN_PORT_FORWARDING_PASSWORD: "e8*Vu8GeMFZBS*"
      SERVER_NAMES: "vietnam404"
      HEALTH_SUCCESS_WAIT_DURATION: 180s
      HEALTH_VPN_DURATION_ADDITION: 20s
      FIREWALL_OUTBOUND_SUBNETS: "192.168.9.0/24,192.168.1.0/24"
      VPN_PORT_FORWARDING_STATUS_FILE: "/gluetun/forwarded_port"
      VPN_PORT_FORWARDING_UP_COMMAND: "/bin/sh -c '/usr/bin/wget -O- --retry-connrefused --post-data \"json={\\\"listen_port\\\":{{PORTS}}}\" http://127.0.0.1:8081/api/v2/app/setPreferences 2>&1'"
      TZ: ${TZ}
    ports:
      - target: 8081
        published: "8081"
        protocol: tcp
      - target: 8080
        published: "8080"
        protocol: tcp
      - target: 8000
        published: "17888"
        protocol: tcp
    volumes:
      - type: bind
        source: "${BASEPATH}/${GLUETUN_CONFIG_PATH}"
        target: /gluetun
    restart: on-failure:10
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    labels:
      proxy.aliases: torrents

  SurfsharkTokyo:
    image: qmcgaw/gluetun:latest
    container_name: gluetun_tokyo
    hostname: gluetun_tokyo
    environment:
      HTTP_CONTROL_SERVER_ADDRESS: ":8000"
      HTTPPROXY: "on"
      SERVER_COUNTRIES: Japan
      VPN_SERVICE_PROVIDER: surfshark
      VPN_TYPE: wireguard
      WIREGUARD_ADDRESSES: 10.14.0.2/16
      WIREGUARD_PRIVATE_KEY: SLEqZJNZkgIyH/iN+xe0Km9AdmMjHphhdZcRNByBSE8=
      WIREGUARD_PUBLIC_KEY: at/xg0TT2b1XTgDi4IIpxSUrWhKP3Xx9QK/uQz2xVQY=
      FIREWALL_OUTBOUND_SUBNETS: 192.168.0.0/24
      SHADOWSOCKS: on
      SHADOWSOCKS_PASSWORD: "password"
      TZ: ${TZ}
    ports:
      - target: 8888
        published: "8886"
        protocol: tcp
      - target: 8000
        published: "16806"
        protocol: tcp
      - target: 8388
        published: "8388"
        protocol: tcp
      - target: 8388
        published: "8388"
        protocol: udp
    volumes:
      - type: bind
        source: "${BASEPATH}/${GLUETUN_CONFIG_PATH}"
        target: /gluetun
    restart: on-failure
    labels:
      icon: https://github.com/walkxcode/dashboard-icons/blob/main/png/gluetun.png?raw=true
    cap_add:
      - NET_ADMIN
    networks:
      vpn:
        ipv4_address: 192.168.3.100

  SurfsharkHongKong:
    image: qmcgaw/gluetun:latest
    container_name: gluetun_hongkong
    hostname: gluetun_hongkong
    environment:
      HTTP_CONTROL_SERVER_ADDRESS: ":8000"
      HTTPPROXY: "on"
      SERVER_COUNTRIES: Hong Kong
      VPN_SERVICE_PROVIDER: surfshark
      VPN_TYPE: wireguard
      WIREGUARD_ADDRESSES: 10.14.0.2/16
      WIREGUARD_PRIVATE_KEY: eED0diuFN0mkg712e/wY1LsRlYQ1qDoF1uq/3Z/JT3Y=
      WIREGUARD_PUBLIC_KEY: JYHdktdtuM7inbtsxRKSDpnBVTWQ5+QLZ/cWWmf4VRg=
      FIREWALL_OUTBOUND_SUBNETS: 192.168.0.0/24
      TZ: ${TZ}
    ports:
      - target: 8888
        published: "8887"
        protocol: tcp
      - target: 8000
        published: "16807"
        protocol: tcp
    volumes:
      - type: bind
        source: "${BASEPATH}/${GLUETUN_CONFIG_PATH}"
        target: /gluetun
    restart: on-failure
    labels:
      icon: https://github.com/walkxcode/dashboard-icons/blob/main/png/gluetun.png?raw=true
    cap_add:
      - NET_ADMIN
    networks:
      vpn:
        ipv4_address: 192.168.3.101

  # NordVietnam:
  #   cap_add:
  #       - NET_ADMIN
  #   cpu_shares: 90
  #   command: []
  #   container_name: gluetun_vietnam
  #   environment:
  #       HTTP_CONTROL_SERVER_ADDRESS: ":8000"
  #       HTTPPROXY: "on"
  #       # SERVER_COUNTRIES: Vietnam
  #       VPN_TYPE: wireguard
  #       WIREGUARD_PRIVATE_KEY: d9EblxXtsyT/6A/et6oalVePIbsPvBNQioAdzm/wUT0=
  #       WIREGUARD_PUBLIC_KEY: BWPQLaQNaIh5JnR239ybidMkd7vdytS1+mrQOBlQug8=
  #       VPN_SERVICE_PROVIDER: custom
  #       WIREGUARD_ENDPOINT_IP: 45.80.187.3
  #       WIREGUARD_ENDPOINT_PORT: 51820
  #       WIREGUARD_ADDRESSES: 10.5.0.2/16
  #       DOT: off
  #       DNS_ADDRESS: 103.86.96.100
  #       TZ: Asia/Ho_Chi_Minh
  #   volumes:
  #     - type: bind
  #       source: /mnt/Application/config/gluetun-config
  #       target: /gluetun
  #   hostname: gluetun_vietnam
  #   image: qmcgaw/gluetun:latest
  #   labels:
  #       icon: https://github.com/walkxcode/dashboard-icons/blob/main/png/gluetun.png?raw=true
  #   ports:
  #       - target: 8888
  #         published: "8890"
  #         protocol: tcp
  #       - target: 8000
  #         published: "16890"
  #         protocol: tcp
  #   restart: on-failure
  #   networks:
  #       - vpn

  # NordKorean:
  #   cap_add:
  #     - NET_ADMIN
  #   cpu_shares: 90
  #   command: []
  #   container_name: gluetun_korean
  #   environment:
  #     HTTP_CONTROL_SERVER_ADDRESS: ":8000"
  #     HTTPPROXY: "on"
  #     SERVER_COUNTRIES: South Korea
  #     VPN_TYPE: wireguard
  #     WIREGUARD_PRIVATE_KEY: Dzy2rJYNLJo+wjkaZWMY90et0GFtCS44Z3LML8rABgU=
  #     VPN_SERVICE_PROVIDER: nordvpn
  #     TZ: Asia/Ho_Chi_Minh
  #   hostname: gluetun_korean
  #   image: qmcgaw/gluetun:latest
  #   labels:
  #     icon: https://github.com/walkxcode/dashboard-icons/blob/main/png/gluetun.png?raw=true
  #   ports:
  #     - target: 8888
  #       published: "8885"
  #       protocol: tcp
  #     - target: 8000
  #       published: "16805"
  #       protocol: tcp
  #   restart: on-failure
  #   networks:
  #     - vpn

  # NordUK:
  #   cap_add:
  #     - NET_ADMIN
  #   cpu_shares: 90
  #   command: []
  #   container_name: gluetun_uk
  #   environment:
  #     HTTP_CONTROL_SERVER_ADDRESS: ":8000"
  #     HTTPPROXY: "on"
  #     SERVER_COUNTRIES: United Kingdom
  #     VPN_TYPE: wireguard
  #     WIREGUARD_PRIVATE_KEY: Dzy2rJYNLJo+wjkaZWMY90et0GFtCS44Z3LML8rABgU=
  #     VPN_SERVICE_PROVIDER: nordvpn
  #     TZ: Asia/Ho_Chi_Minh
  #   hostname: gluetun_uk
  #   image: qmcgaw/gluetun:latest
  #   labels:
  #     icon: https://github.com/walkxcode/dashboard-icons/blob/main/png/gluetun.png?raw=true
  #   ports:
  #     - target: 8888
  #       published: "8887"
  #       protocol: tcp
  #     - target: 8000
  #       published: "16807"
  #       protocol: tcp
  #   restart: on-failure
  #   networks:
  #     - vpn

  # NordSingapore:
  #   cap_add:
  #     - NET_ADMIN
  #   cpu_shares: 90
  #   command: []
  #   container_name: gluetun_singapore
  #   environment:
  #     HTTP_CONTROL_SERVER_ADDRESS: ":8000"
  #     HTTPPROXY: "on"
  #     SERVER_COUNTRIES: Singapore
  #     VPN_TYPE: wireguard
  #     WIREGUARD_PRIVATE_KEY: Dzy2rJYNLJo+wjkaZWMY90et0GFtCS44Z3LML8rABgU=
  #     VPN_SERVICE_PROVIDER: nordvpn
  #     TZ: Asia/Ho_Chi_Minh
  #   hostname: gluetun_singapore
  #   image: qmcgaw/gluetun:latest
  #   labels:
  #     icon: https://github.com/walkxcode/dashboard-icons/blob/main/png/gluetun.png?raw=true
  #   ports:
  #     - target: 8888
  #       published: "8889"
  #       protocol: tcp
  #     - target: 8000
  #       published: "16809"
  #       protocol: tcp
  #   restart: on-failure
  #   networks:
  #     - vpn

  # NordCanada:
  #   cap_add:
  #     - NET_ADMIN
  #   cpu_shares: 90
  #   command: []
  #   container_name: gluetun_canada
  #   environment:
  #     HTTP_CONTROL_SERVER_ADDRESS: ":8000"
  #     HTTPPROXY: "on"
  #     SERVER_COUNTRIES: Canada
  #     VPN_TYPE: wireguard
  #     WIREGUARD_PRIVATE_KEY: Dzy2rJYNLJo+wjkaZWMY90et0GFtCS44Z3LML8rABgU=
  #     VPN_SERVICE_PROVIDER: nordvpn
  #     TZ: Asia/Ho_Chi_Minh
  #   hostname: gluetun_canada
  #   image: qmcgaw/gluetun:latest
  #   labels:
  #     icon: https://github.com/walkxcode/dashboard-icons/blob/main/png/gluetun.png?raw=true
  #   ports:
  #     - target: 8888
  #       published: "8892"
  #       protocol: tcp
  #     - target: 8000
  #       published: "16892"
  #       protocol: tcp
  #   restart: on-failure
  #   networks:
  #     - vpn

  # PIA_Canada:
  #   cap_add:
  #     - NET_ADMIN
  #   cpu_shares: 90
  #   command: []
  #   container_name: gluetun_canada
  #   environment:
  #     HTTP_CONTROL_SERVER_ADDRESS: ":8000"
  #     HTTPPROXY: "on"
  #     # SERVER_COUNTRIES: Singapore # only use in openvpn
  #     VPN_SERVICE_PROVIDER: custom
  #     VPN_TYPE: wireguard
  #     WIREGUARD_ENDPOINT_IP: 181.214.153.155
  #     WIREGUARD_ENDPOINT_PORT: 1337
  #     WIREGUARD_ADDRESSES: 10.26.133.240/32
  #     WIREGUARD_PRIVATE_KEY: aLVMN4Gty4wwBmVmFYTOj4ohs9hHt8FPWB+IyqqYkUM=
  #     WIREGUARD_PUBLIC_KEY: TXj93WcUt80vQQ2LpfRjGgKYcEtOaMDLS60ol+x7o10=
  #     TZ: Asia/Ho_Chi_Minh
  #   hostname: gluetun_canada
  #   image: qmcgaw/gluetun:latest
  #   labels:
  #     icon: https://github.com/walkxcode/dashboard-icons/blob/main/png/gluetun.png?raw=true
  #   ports:
  #     - target: 8888
  #       published: "8892"
  #       protocol: tcp
  #     - target: 8000
  #       published: "16892"
  #       protocol: tcp
  #   restart: on-failure
  #   networks:
  #     - vpn
