services:
  gluetun_mt:
    image: qmcgaw/gluetun
    network_mode: bridge
    container_name: gluetun_mt
    hostname: gluetun_mt
    environment:
      HTTPPROXY: "on"
      HTTPPROXY_USER: "telemt"
      HTTPPROXY_PASSWORD: "telemt"
      HTTPPROXY_LOG: "on"
      HTTPPROXY_LISTENING_ADDRESS: ":8888"
      HTTP_CONTROL_SERVER_ADDRESS: ":8000"
      HTTPPROXY_STEALTH: "on"
      # VPN_SERVICE_PROVIDER: expressvpn
      # OPENVPN_USER: ${OPENVPN_USER}
      # OPENVPN_PASSWORD: ${OPENVPN_PASSWORD}
      # SERVER_COUNTRIES: ${SERVER_COUNTRIES}
      VPN_SERVICE_PROVIDER: custom
      VPN_TYPE: wireguard
      WIREGUARD_ENDPOINT_IP: ${WIREGUARD_ENDPOINT_IP}
      WIREGUARD_ENDPOINT_PORT: ${WIREGUARD_ENDPOINT_PORT}
      WIREGUARD_PRESHARED_KEY: ${WIREGUARD_PRESHARED_KEY}
      WIREGUARD_ADDRESSES: ${WIREGUARD_ADDRESSES}
      WIREGUARD_PRIVATE_KEY: ${WIREGUARD_PRIVATE_KEY}
      WIREGUARD_PUBLIC_KEY: ${WIREGUARD_PUBLIC_KEY}
      TZ: ${TZ}
    ports:
      - traffic: 443
        published: "17443"
        protocol: tcp
      - target: 993
        published: "993"
        protocol: tcp
      - target: 8888
        published: "17888"
        protocol: tcp
    volumes:
      - type: bind
        source: "${BASEPATH}/${GLUETUN_CONFIG_PATH}"
        target: /gluetun
    restart: on-failure:10
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    labels:
      proxy.aliases: mtg.picityvietnam.com, sn.picityvietnam.com
      proxy.#1.port: 993
      proxy.#2.port: 17443
      proxy.#1.no_tls_verify: true
      # proxy.#1.relay_proxy_protocol_header: true
    
  telemt:
    image: ghcr.io/telemt/telemt:3.3.28
    container_name: telemt
    restart: unless-stopped
    # Allow caching 'proxy-secret' in read-only container
    working_dir: /run/telemt
    # Use the gluetun_mt or expressvpn network so telemt's traffic goes through the VPN
    network_mode: "service:${VPN_PROVIDER}"
    tmpfs:
      - /run/telemt:rw,mode=1777,size=1m
    volumes:
      - type: bind
        source: "${BASEPATH}/${MTPROTO_CONFIG_PATH}/config.toml"
        target: /run/telemt/config.toml
        read_only: true
    environment:
      RUST_LOG: info
      TZ: ${TZ}
    # Uncomment this line if you want to use host network for IPv6, but bridge is default and usually better
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE # allow binding to port 443
    read_only: true
    security_opt:
      - no-new-privileges:true
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    labels:
      proxy.exclude: true