services:
  gluetun_claw:
    image: qmcgaw/gluetun
    network_mode: bridge
    container_name: gluetun_claw
    hostname: gluetun_claw
    environment:
      SERVER_COUNTRIES: ${SERVER_COUNTRIES}
      VPN_SERVICE_PROVIDER: protonvpn
      VPN_TYPE: wireguard
      WIREGUARD_PRIVATE_KEY: ${WIREGUARD_PRIVATE_KEY}
      FIREWALL_OUTBOUND_SUBNETS: "192.168.1.0/24"
      TZ: ${TZ}
    ports:
      - target: 42617
        published: "42617"
        protocol: tcp
    volumes:
      - type: bind
        source: "${BASEPATH}/${GLUETUN_CONFIG_PATH}"
        target: /gluetun
    restart: on-failure:10
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    labels:
      proxy.aliases: zeroclaw.picityvietnam.com
      proxy.#1.port: 42617
      # proxy.#1.relay_proxy_protocol_header: true
    
  zeroclaw:
    image: ghcr.io/zeroclaw-labs/zeroclaw:latest
    container_name: zeroclaw
    restart: unless-stopped
    network_mode: "service:gluetun_claw"
    volumes:
      - type: bind
        source: "/mnt/Application/config/zeroclaw"
        target: "/zeroclaw-data"
    extra_hosts:
      - "qlvb.local:123.30.143.217"

    command: "channel start"
    environment:
      RUST_LOG: info
      TZ: ${TZ}
    labels:
      proxy.exclude: true
      

    
