services:
  pocketid:
    image: ghcr.io/pocket-id/pocket-id:v2
    network_mode: bridge
    hostname: pocketid
    container_name: pocketid
    environment:
      TZ: ${TZ}
      PGID: ${PGID}
      PUID: ${PUID}
      TRUST_PROXY: "true"
      # INTERNAL_APP_URL: "${LOCALHOST}:1411"
      ENCRYPTION_KEY: ${SECRET}
      # APP_URL: "https://pocketid.${CF_DOMAIN}"
      DB_CONNECTION_STRING: data/pocket-id.db # "postgresql://${POCKETID_DB_NAME}:${POCKETID_DB_NAME}@${LOCAL_VPS_IP}:${POSTGRES_PORT}/${POCKETID_DB_NAME}"
      MAXMIND_LICENSE_KEY_FILE: "/app/data/${MAXMIND_LICENSE_KEY_FILE}"
    ports:
      - target: 1411
        published: 1411
        protocol: tcp
    volumes:
      - type: bind
        source: "${BASEPATH}/${APP_CONFIG_PATH}"
        target: /app/data
    restart: unless-stopped
    labels:
      proxy.aliases: pocketid
      proxy.#1.port: 1411
