services:
  tinyauth:
    image: ghcr.io/steveiliop56/tinyauth:v3
    network_mode: bridge
    hostname: tinyauth
    container_name: tinyauth
    environment:
      TZ: ${TZ}
      PORT: 10000
      COOKIE_SECURE: "true"
      APP_TITLE: "OSCE HomeLab"
      APP_URL: "https://tinyauth.${CF_DOMAIN}"
      DOCKER_HOST: "tcp://127.0.0.1:2375"
      DISABLE_CONTINUE: true
      OAUTH_WHITELIST: ${OAUTH_WHITELIST}
      OAUTH_AUTO_REDIRECT: generic
      GENERIC_NAME: "Pocket ID"
      GENERIC_AUTH_URL: "${POCKETID_OIDC_ISSUER_URL}/authorize"
      GENERIC_TOKEN_URL: "${POCKETID_OIDC_ISSUER_URL}/api/oidc/token"
      GENERIC_USER_URL: "${POCKETID_OIDC_ISSUER_URL}/api/oidc/userinfo"
      GENERIC_CLIENT_ID: ${POCKETID_OIDC_CLIENT_ID}
      GENERIC_CLIENT_SECRET: ${POCKETID_OIDC_CLIENT_SECRET}
      GENERIC_SCOPES: ${POCKETID_OIDC_SCOPES}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      SECRET: ${SECRET}
    ports:
      - target: 10000
        published: 10000
        protocol: tcp
    restart: unless-stopped
    labels:
      proxy.aliases: tinyauth
      proxy.#1.port: 10000
      proxy.#1.middlewares.real_ip: |
        header: X-Real-IP
        from:
          - 127.0.0.1
          - 192.168.0.0/16
          - 172.16.0.0/12
          - 10.0.0.0/8
        recursive: true