services:
  pocketid:
    image: ghcr.io/pocket-id/pocket-id:v1
    network_mode: bridge
    hostname: pocketid
    container_name: pocketid
    environment:
      TZ: ${TZ}
      PGID: ${PGID}
      PUID: ${PUID}
      TRUST_PROXY: "true"
      ENCRYPTION_KEY: ${SECRET}
      APP_URL: "https://pocketid.${CF_DOMAIN}"
      DB_PROVIDER: "postgres"
      DB_CONNECTION_STRING: "postgresql://${POCKETID_DB_NAME}:${POCKETID_DB_NAME}@${LOCALHOST}:${POSTGRES_PORT}/${POCKETID_DB_NAME}"
      MAXMIND_LICENSE_KEY_FILE: "/app/data/${MAXMIND_LICENSE_KEY_FILE}"
    ports:
      - target: 1411
        published: 1411
        protocol: tcp
    volumes:
      - type: bind
        source: "${BASEPATH}/${APP_CONFIG_PATH}"
        target: /app/data
    restart: unless-stopped
    labels:
      proxy.aliases: pocketid
      proxy.#1.port: 1411
  tinyauth:
    image: ghcr.io/steveiliop56/tinyauth:v3
    network_mode: bridge
    hostname: tinyauth
    container_name: tinyauth
    environment:
      TZ: ${TZ}
      PORT: 10000
      COOKIE_SECURE: "true"
      LOG_LEVEL: 0
      APP_TITLE: "OSCE HomeLab"
      APP_URL: "https://tinyauth.${CF_DOMAIN}"
      DOCKER_HOST: "tcp://${LOCALHOST}:2375"
      OAUTH_WHITELIST: ${OAUTH_WHITELIST}
      OAUTH_AUTO_REDIRECT: generic
      GENERIC_NAME: "Pocket ID"
      GENERIC_AUTH_URL: "${POCKETID_OIDC_ISSUER_URL}/authorize"
      GENERIC_TOKEN_URL: "${POCKETID_OIDC_ISSUER_URL}/api/oidc/token"
      GENERIC_USER_URL: "${POCKETID_OIDC_ISSUER_URL}/api/oidc/userinfo"
      GENERIC_CLIENT_ID: ${POCKETID_OIDC_CLIENT_ID}
      GENERIC_CLIENT_SECRET: ${POCKETID_OIDC_CLIENT_SECRET}
      GENERIC_SCOPES: ${POCKETID_OIDC_SCOPES}
      SECRET: ${SECRET}
    ports:
      - target: 10000
        published: "10000"
        protocol: tcp
    restart: unless-stopped
    labels:
      proxy.aliases: tinyauth
      proxy.#1.port: 10000