services:
  filebrowser:
    image: gtstef/filebrowser:beta-slim
    network_mode: bridge
    container_name: filebrowser
    hostname: filebrowser
    mem_limit: 512m   # RAM tối đa
    cpus: "0.3"       # Tối đa 50% CPU
    environment:
      FILEBROWSER_CONFIG: "data/config.yaml"
      TZ: ${TZ}
    ports:
      - target: 80
        published: "1480"
        protocol: tcp
    volumes:
      - type: bind
        source: "${BASEPATH}/${APP_CONFIG_PATH}"
        target: /home/filebrowser/data
      - type: bind
        source: "/"
        target: /homelab
    restart: unless-stopped
    labels:
      proxy.aliases: file
      proxy.#1.port: 1480
      proxy.idle_timeout: 5m