services:
  filebrowser:
    image: gtstef/filebrowser
    network_mode: bridge
    container_name: filebrowser
    hostname: filebrowser
    environment:
      FILEBROWSER_CONFIG: "data/config.yaml"
      TZ: ${TZ}
    ports:
      - target: 80
        published: "1480"
        protocol: tcp
    volumes:
      - type: bind
        source: "${BASEPATH}/${APP_CONFIG_PATH}"
        target: /home/filebrowser/data
      - type: bind
        source: "/"
        target: /homelab
    restart: unless-stopped