services:
  frontend:
    image: ghcr.io/yusing/godoxy-frontend:${TAG:-latest}
    network_mode: bridge
    container_name: godoxy-frontend
    hostname: godoxy-frontend
    environment:
      TZ: ${TZ}
      GODOXY_API_ADDR: ${GODOXY_API_ADDR}
    restart: unless-stopped
    # user: ${GODOXY_UID:-1000}:${GODOXY_GID:-1000}
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - all
    depends_on:
      - app
      # proxy.#1.middlewares.cidr_whitelist: |
      #   status: 403
      #   message: IP not allowed
      #   allow:
      #     - 127.0.0.1
      #     - 10.0.0.0/8
      #     - 192.168.0.0/16
      #     - 172.16.0.0/12
  app:
    image: ghcr.io/yusing/godoxy:${TAG:-latest}
    network_mode: host # do not change this
    container_name: godoxy-proxy
    hostname: godoxy-proxy
    environment:
      GOTRACEBACK: all
      GODOXY_DEBUG: true
      DOCKER_HOST: "tcp://${SOCKET_PROXY_LISTEN_ADDR:-127.0.0.1:2375}"
      LEGO_DISABLE_CNAME_SUPPORT: 1
      GODOXY_API_JWT_SECRET: ${GODOXY_API_JWT_SECRET}
      GODOXY_OIDC_ISSUER_URL: ${POCKETID_OIDC_ISSUER_URL}
      GODOXY_OIDC_CLIENT_ID: ${GODOXY_OIDC_CLIENT_ID}
      GODOXY_OIDC_CLIENT_SECRET: ${GODOXY_OIDC_CLIENT_SECRET}
      GODOXY_OIDC_SCOPES: ${GODOXY_OIDC_SCOPES}
      GODOXY_OIDC_ALLOWED_USERS: ${GODOXY_OIDC_ALLOWED_USERS}
      GODOXY_OIDC_ALLOWED_GROUPS: ${GODOXY_OIDC_ALLOWED_GROUPS}
      GODOXY_API_ADDR: ${GODOXY_API_ADDR}
      TZ: ${TZ}
    volumes:
      - ${BASEPATH}/${APP_CONFIG_PATH}/config:/app/config
      - ${BASEPATH}/${APP_CONFIG_PATH}/logs:/app/logs
      - ${BASEPATH}/${APP_CONFIG_PATH}/error_pages:/app/error_pages:ro
      - ${BASEPATH}/${APP_CONFIG_PATH}/data:/app/data
      - ${BASEPATH}/${APP_CONFIG_PATH}/certs:/app/certs
    restart: always
    user: ${GODOXY_UID:-1000}:${GODOXY_GID:-1000}
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE