services:
  frontend:
    image: ghcr.io/yusing/godoxy-frontend:${TAG:-latest}
    network_mode: bridge # do not change this
    container_name: godoxy-frontend
    hostname: godoxy-frontend
    environment:
      TZ: ${TZ}
    restart: unless-stopped
    user: ${GODOXY_UID:-1000}:${GODOXY_GID:-1000}
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - all
    depends_on:
      - app
      # proxy.#1.middlewares.cidr_whitelist: |
      #   status: 403
      #   message: IP not allowed
      #   allow:
      #     - 127.0.0.1
      #     - 10.0.0.0/8
      #     - 192.168.0.0/16
      #     - 172.16.0.0/12
  # agent:
  #   image: "ghcr.io/yusing/godoxy-agent:latest"
  #   container_name: godoxy-agent
  #   restart: always
  #   network_mode: host # do not change this
  #   environment:
  #     AGENT_NAME: "godoxy-agent"
  #     AGENT_PORT: "8890"
  #     AGENT_CA_CERT: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJsakNDQVR1Z0F3SUJBZ0lRR1VTMVcyOWtta2U4cndlUHp5eldkVEFLQmdncWhrak9QUVFEQWpBb01ROHcKRFFZRFZRUUtFd1pIYjBSdmVIa3hGVEFUQmdOVkJBTVRER2R2Wkc5NGVTNWhaMlZ1ZERBZ0Z3MHlOVEE1TURNdwpOelE0TWpCYUdBOHpNREkxTURrd016QTNORGd5TUZvd0tERVBNQTBHQTFVRUNoTUdSMjlFYjNoNU1SVXdFd1lEClZRUURFd3huYjJSdmVIa3VZV2RsYm5Rd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFRdUR3QlMKVnRJdzdYdWovVE5wd3NwSmk5SSt1MWs2eUpEZnQxdWg4Z3hVQlB6cVlRQ2xZRVNBVitmSUxRbUowZGNpNCs5cgo3Q2oyM25uSmE0bjVTaGVTbzBVd1F6QU9CZ05WSFE4QkFmOEVCQU1DQVFZd0VnWURWUjBUQVFIL0JBZ3dCZ0VCCi93SUJBREFkQmdOVkhRNEVGZ1FVTlVqN0JVcitXRDQzUkd3aklXOWdJY25WUWNRd0NnWUlLb1pJemowRUF3SUQKU1FBd1JnSWhBTGN0ZzJtUElId3BDZ2lhZHRxUFZscUtyM2VnZEh6bldvN1RaeWdkNGcwZEFpRUFzcHVSZzJMawp0SFJqaXdxQjlCVUFVQzZVUnpoYWlJRGp0aHBvampYamY1VT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=;LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUM2L25USnZFZmYrYk1hT2hRQThRTXk3VmVEeGdsOHhSR2RJQTA4YVB2aGdvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFTGc4QVVsYlNNTzE3by8wemFjTEtTWXZTUHJ0Wk9zaVEzN2Rib2ZJTVZBVDg2bUVBcFdCRQpnRmZueUMwSmlkSFhJdVB2YSt3bzl0NTV5V3VKK1VvWGtnPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo="
  #     AGENT_SSL_CERT: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJvVENDQVVlZ0F3SUJBZ0lRTHlLaVdhL3h5aW52bzIzRGcwT1FPekFLQmdncWhrak9QUVFEQWpBb01ROHcKRFFZRFZRUUtFd1pIYjBSdmVIa3hGVEFUQmdOVkJBTVRER2R2Wkc5NGVTNWhaMlZ1ZERBZ0Z3MHlOVEE1TURNdwpOelE0TWpCYUdBOHpNREkxTURrd016QTNORGd5TUZvd09URVBNQTBHQTFVRUNoTUdSMjlFYjNoNU1ROHdEUVlEClZRUUxFd1pUWlhKMlpYSXhGVEFUQmdOVkJBTVRER2R2Wkc5NGVTNWhaMlZ1ZERCWk1CTUdCeXFHU000OUFnRUcKQ0NxR1NNNDlBd0VIQTBJQUJEOFJOMWxhcS9SREc5Z2lxOGt1VUp3UmRsUHd3YzlTR29mN3lxeEZqdktPN01zLwpJUFpITHg1Q0JoMWpPTHZXSlE0dTZKL083QWF5Z1VkM0FPQWF4c0dqUURBK01BNEdBMVVkRHdFQi93UUVBd0lICmdEQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBVEFYQmdOVkhSRUVFREFPZ2d4bmIyUnZlSGt1WVdkbGJuUXcKQ2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnR0t2SU1BRUd6Z3g1eW4zT0ZUM25ZeklXY2dxREJZUENaUFRhbG4wRAplVjhDSVFDS2h6OEw3MndvS0FqMGFNbTBLRkp6UGdoZncyZTVJb2wyenp4QXo0V0lVZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K;LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSU9DMkVWbzBiU2NXOFppZjFIMkE1ekk1Y1NmOHFoVExrZnQ2UkpPeDNleU9vQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFUHhFM1dWcXI5RU1iMkNLcnlTNVFuQkYyVS9EQnoxSWFoL3ZLckVXTzhvN3N5ejhnOWtjdgpIa0lHSFdNNHU5WWxEaTdvbjg3c0JyS0JSM2NBNEJyR3dRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo="
  #     # use agent as a docker socket proxy: [host]:port
  #     # set LISTEN_ADDR to enable (e.g. 127.0.0.1:2375)
  #     # Không sửa đoạn này, docker socket proxy của godoxy cần tách biệt port với komodo
  #     LISTEN_ADDR: 127.0.0.1:2376
  #     POST: false
  #     ALLOW_RESTARTS: false
  #     ALLOW_START: false
  #     ALLOW_STOP: false
  #     AUTH: false
  #     BUILD: false
  #     COMMIT: false
  #     CONFIGS: false
  #     CONTAINERS: false
  #     DISTRIBUTION: false
  #     EVENTS: true
  #     EXEC: false
  #     GRPC: false
  #     IMAGES: false
  #     INFO: false
  #     NETWORKS: false
  #     NODES: false
  #     PING: true
  #     PLUGINS: false
  #     SECRETS: false
  #     SERVICES: false
  #     SESSION: false
  #     SWARM: false
  #     SYSTEM: false
  #     TASKS: false
  #     VERSION: true
  #     VOLUMES: false
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - ${BASEPATH}/${APP_CONFIG_PATH}/agents:/app/data
  app:
    image: ghcr.io/yusing/godoxy:${TAG:-latest}
    network_mode: host
    container_name: godoxy-proxy
    hostname: godoxy-proxy
    environment:
      DOCKER_HOST: "tcp://${SOCKET_PROXY_LISTEN_ADDR:-127.0.0.1:2375}"
      LEGO_DISABLE_CNAME_SUPPORT: 1
      GODOXY_API_JWT_SECRET: ${GODOXY_API_JWT_SECRET}
      GODOXY_OIDC_ISSUER_URL: ${POCKETID_OIDC_ISSUER_URL}
      GODOXY_OIDC_CLIENT_ID: ${GODOXY_OIDC_CLIENT_ID}
      GODOXY_OIDC_CLIENT_SECRET: ${GODOXY_OIDC_CLIENT_SECRET}
      GODOXY_OIDC_SCOPES: ${GODOXY_OIDC_SCOPES}
      GODOXY_OIDC_ALLOWED_USERS: ${GODOXY_OIDC_ALLOWED_USERS}
      GODOXY_OIDC_ALLOWED_GROUPS: ${GODOXY_OIDC_ALLOWED_GROUPS}
      GODOXY_API_ADDR: ${GODOXY_API_ADDR}
      TZ: ${TZ}
    volumes:
      - ${BASEPATH}/${APP_CONFIG_PATH}/config:/app/config
      - ${BASEPATH}/${APP_CONFIG_PATH}/logs:/app/logs
      - ${BASEPATH}/${APP_CONFIG_PATH}/error_pages:/app/error_pages:ro
      - ${BASEPATH}/${APP_CONFIG_PATH}/data:/app/data
      - ${BASEPATH}/${APP_CONFIG_PATH}/certs:/app/certs
    restart: always
    user: ${GODOXY_UID:-1000}:${GODOXY_GID:-1000}
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
