services:
  frontend:
    image: ghcr.io/yusing/godoxy-frontend:${TAG:-latest}
    network_mode: host # do not change this
    container_name: godoxy-frontend
    hostname: godoxy-frontend
    environment:
      HOSTNAME: 192.168.1.3
      PORT: ${GODOXY_FRONTEND_PORT}
      TZ: ${TZ}
    restart: unless-stopped
    user: ${GODOXY_UID:-1000}:${GODOXY_GID:-1000}
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - all
    depends_on:
      - app
    labels:
      proxy.aliases: ${GODOXY_FRONTEND_ALIASES:-godoxy}
      proxy.#1.port: ${GODOXY_FRONTEND_PORT:-3000}
      # proxy.#1.middlewares.cidr_whitelist: |
      #   status: 403
      #   message: IP not allowed
      #   allow:
      #     - 127.0.0.1
      #     - 10.0.0.0/8
      #     - 192.168.0.0/16
      #     - 172.16.0.0/12
  agent:
    image: "ghcr.io/yusing/godoxy-agent:latest"
    container_name: godoxy-agent
    restart: always
    network_mode: host # do not change this
    environment:
      AGENT_NAME: "docker-godoxy-agent"
      AGENT_PORT: "8891"
      AGENT_CA_CERT: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJsRENDQVR1Z0F3SUJBZ0lRYTR4Smwyd0xLZFc1ZHVWWUNiUnQ0akFLQmdncWhrak9QUVFEQWpBb01ROHcKRFFZRFZRUUtFd1pIYjBSdmVIa3hGVEFUQmdOVkJBTVRER2R2Wkc5NGVTNWhaMlZ1ZERBZ0Z3MHlOVEE1TURNdwpOek13TlRWYUdBOHpNREkxTURrd016QTNNekExTlZvd0tERVBNQTBHQTFVRUNoTUdSMjlFYjNoNU1SVXdFd1lEClZRUURFd3huYjJSdmVIa3VZV2RsYm5Rd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFSc09qa1UKNmVHOEFNN1lvQmM2ZFFDT1pWRUtLWmtycVMvdkxzUjcybnBiTWY1Y3J4VmpFOVNZYXc2RWx4MHlwaTRhc3VWago2RWlJeGF5dEVSeXl4NzJWbzBVd1F6QU9CZ05WSFE4QkFmOEVCQU1DQVFZd0VnWURWUjBUQVFIL0JBZ3dCZ0VCCi93SUJBREFkQmdOVkhRNEVGZ1FVVjkwMnE1VGlsWURNRUJzZ3k3c0VQT1BqTWxZd0NnWUlLb1pJemowRUF3SUQKUndBd1JBSWdOaDh0OEI1NzFEdWkxQ2p1d3R4Nm1NK2c4UEhQbndrZHkzYUxES1ZKQ3ZZQ0lGeW1BTmJNZi80bwpNQmxWRUYyc1lmbUlQZGZWUG1uMlA2YStoNkVVVlQ1cAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==;LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSVBBMU5raUN3YXBRN2puc3VUMVlpZkNtSUVJbUJKUXk3Z3d1N2ZFcEk4QmlvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFYkRvNUZPbmh2QURPMktBWE9uVUFqbVZSQ2ltWks2a3Y3eTdFZTlwNld6SCtYSzhWWXhQVQptR3NPaEpjZE1xWXVHckxsWStoSWlNV3NyUkVjc3NlOWxRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo="
      AGENT_SSL_CERT: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJvRENDQVVlZ0F3SUJBZ0lRSjBSV21RN3ZZS1JwaUtzZTNIMnJvVEFLQmdncWhrak9QUVFEQWpBb01ROHcKRFFZRFZRUUtFd1pIYjBSdmVIa3hGVEFUQmdOVkJBTVRER2R2Wkc5NGVTNWhaMlZ1ZERBZ0Z3MHlOVEE1TURNdwpOek13TlRWYUdBOHpNREkxTURrd016QTNNekExTlZvd09URVBNQTBHQTFVRUNoTUdSMjlFYjNoNU1ROHdEUVlEClZRUUxFd1pUWlhKMlpYSXhGVEFUQmdOVkJBTVRER2R2Wkc5NGVTNWhaMlZ1ZERCWk1CTUdCeXFHU000OUFnRUcKQ0NxR1NNNDlBd0VIQTBJQUJNTEp3SHcyS01LN0lKWGp6a0VvQm81bnIxZkRPT3BBUlVEakIrUVppN0NVNFJyagoxYkpZaFF5bHdSYWswVHpxQ2JPRUJMTzc1cmZpSXkvamtXNjhkQmVqUURBK01BNEdBMVVkRHdFQi93UUVBd0lICmdEQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBVEFYQmdOVkhSRUVFREFPZ2d4bmIyUnZlSGt1WVdkbGJuUXcKQ2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnWTQ2Q2pzM3oweFcxQWVlUXNndUZ3NXFKYWZGSEZBUHpuVDAyd0VmYwpJcUFDSUdtSWpIQ0plTWxJczJJa0FnTU5lN2FSejlZREU0cEdOM2pTcWYzNlZlVXYKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=;LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSU85V0F0MTFzSUlRTWdXdW5WaHpjbE0wQkkxRTV2YjFxcVZ0aXY4cmZEYnVvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFd3NuQWZEWW93cnNnbGVQT1FTZ0dqbWV2VjhNNDZrQkZRT01INUJtTHNKVGhHdVBWc2xpRgpES1hCRnFUUlBPb0pzNFFFczd2bXQrSWpMK09SYnJ4MEZ3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo="
      # use agent as a docker socket proxy: [host]:port
      # set LISTEN_ADDR to enable (e.g. 127.0.0.1:2375)
      LISTEN_ADDR: 127.0.0.1:2375
      POST: false
      ALLOW_RESTARTS: false
      ALLOW_START: false
      ALLOW_STOP: false
      AUTH: false
      BUILD: false
      COMMIT: false
      CONFIGS: false
      CONTAINERS: false
      DISTRIBUTION: false
      EVENTS: true
      EXEC: false
      GRPC: false
      IMAGES: false
      INFO: false
      NETWORKS: false
      NODES: false
      PING: true
      PLUGINS: false
      SECRETS: false
      SERVICES: false
      SESSION: false
      SWARM: false
      SYSTEM: false
      TASKS: false
      VERSION: true
      VOLUMES: false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${BASEPATH}/${APP_CONFIG_PATH}/agents:/app/data
  app:
    image: ghcr.io/yusing/godoxy:${TAG:-latest}
    network_mode: host # do not change this
    container_name: godoxy-proxy
    hostname: godoxy-proxy
    environment:
      DOCKER_HOST: "tcp://${SOCKET_PROXY_LISTEN_ADDR:-127.0.0.1:2375}"
      LEGO_DISABLE_CNAME_SUPPORT: 1
      GODOXY_API_JWT_SECRET: ${GODOXY_API_JWT_SECRET}
      GODOXY_OIDC_ISSUER_URL: ${POCKETID_OIDC_ISSUER_URL}
      GODOXY_OIDC_CLIENT_ID: ${POCKETID_OIDC_CLIENT_ID}
      GODOXY_OIDC_CLIENT_SECRET: ${POCKETID_OIDC_CLIENT_SECRET}
      GODOXY_OIDC_SCOPES: ${POCKETID_OIDC_SCOPES}
      GODOXY_OIDC_ALLOWED_USERS: ${POCKETID_OIDC_ALLOWED_USERS}
      GODOXY_OIDC_ALLOWED_GROUPS: ${POCKETID_OIDC_ALLOWED_GROUPS}
      TZ: ${TZ}
    volumes:
      - ${BASEPATH}/${APP_CONFIG_PATH}/config:/app/config
      - ${BASEPATH}/${APP_CONFIG_PATH}/logs:/app/logs
      - ${BASEPATH}/${APP_CONFIG_PATH}/error_pages:/app/error_pages:ro
      - ${BASEPATH}/${APP_CONFIG_PATH}/data:/app/data
      - ${BASEPATH}/${APP_CONFIG_PATH}/certs:/app/certs
      # - /path/to/certs/cert.crt:/app/certs/cert.crt
      # - /path/to/certs/priv.key:/app/certs/priv.key
    restart: always
    user: ${GODOXY_UID:-1000}:${GODOXY_GID:-1000}
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
