services:
  frontend:
    image: ghcr.io/yusing/godoxy-frontend:${TAG:-latest}
    network_mode: host # do not change this
    container_name: godoxy-frontend
    hostname: godoxy-frontend
    environment:
      HOSTNAME: 192.168.1.3
      PORT: ${GODOXY_FRONTEND_PORT}
      TZ: ${TZ}
    restart: unless-stopped
    user: ${GODOXY_UID:-1000}:${GODOXY_GID:-1000}
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - all
    depends_on:
      - app
    labels:
      proxy.aliases: ${GODOXY_FRONTEND_ALIASES:-godoxy}
      proxy.#1.port: ${GODOXY_FRONTEND_PORT:-3000}
      # proxy.#1.middlewares.cidr_whitelist: |
      #   status: 403
      #   message: IP not allowed
      #   allow:
      #     - 127.0.0.1
      #     - 10.0.0.0/8
      #     - 192.168.0.0/16
      #     - 172.16.0.0/12

  app:
    image: ghcr.io/yusing/godoxy:${TAG:-latest}
    network_mode: host # do not change this
    container_name: godoxy-proxy
    hostname: godoxy-proxy
    environment:
      DOCKER_HOST: "tcp://${SOCKET_PROXY_LISTEN_ADDR:-127.0.0.1:2375}"
      LEGO_DISABLE_CNAME_SUPPORT: 1
      TZ: ${TZ}
    volumes:
      - ${BASEPATH}/${APP_CONFIG_PATH}/config:/app/config
      - ${BASEPATH}/${APP_CONFIG_PATH}/logs:/app/logs
      - ${BASEPATH}/${APP_CONFIG_PATH}/error_pages:/app/error_pages:ro
      - ${BASEPATH}/${APP_CONFIG_PATH}/data:/app/data
      - ${BASEPATH}/${APP_CONFIG_PATH}/certs:/app/certs
      # - /path/to/certs/cert.crt:/app/certs/cert.crt
      # - /path/to/certs/priv.key:/app/certs/priv.key
    restart: always
    user: ${GODOXY_UID:-1000}:${GODOXY_GID:-1000}
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
