services:
  alist:
    image: xhofe/alist:latest-aria2
    network_mode: bridge
    container_name: alist
    hostname: alist
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
      UMASK: "022"
    expose:
      - 6800
    ports:
      - target: 5244
        published: "5244"
        protocol: tcp
      - target: 5246
        published: "5246"
        protocol: tcp
    volumes:
      - type: bind
        source: "${BASEPATH}/${ALIST_CONFIG_PATH}"
        target: /opt/alist/data
      - type: bind
        source: "${INFUSE_MEDIA_STORAGE_PATH}"
        target: /media
      - type: bind
        source: "${MISC_STORAGE_PATH}"
        target: /storage
      - type: bind
        source: "${APPLICATION_STORAGE_PATH}"
        target: /downloads
    restart: unless-stopped
    labels:
      proxy.aliases: alist
      proxy.#1.middlewares.forwardauth.headers: Authorization
      proxy.#1.port: 5244
      proxy.#1.homepage: |
        name: "Alist"
        icon: "@walkxcode/alist.svg"
        category: "Storage"
        
  rclone:
    image: rclone/rclone:latest
    network_mode: bridge
    container_name: rclone
    hostname: rclone
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
      UMASK: "022"
    ports:
      - target: 5572
        published: "18572"
        protocol: tcp
    volumes:
      - type: bind
        source: "${BASEPATH}/${RClONE_CONFIG_PATH}"
        target: /config/rclone
        bind: {}
      - type: bind
        source: "${BASEPATH}/${RClONE_CONFIG_PATH}/logs"
        target: /logs
        bind: {}
      - type: bind
        source: "${INFUSE_MEDIA_STORAGE_PATH}"
        target: /media
        bind: {}
      - type: bind
        source: "${MISC_STORAGE_PATH}/Downloads"
        target: /pyloads-download
        bind: {}
    cpu_shares: 90
    command:
      - rcd
      - --rc-web-gui
      - --rc-addr
      - :5572
      - --rc-user
      - mahdi
      - --rc-pass
      # - serve
      # - http
      # - Onedrive_Personal
      # - --addr
      # - :5572
      # - --user
      # - mahdi
      # - --pass
      - quadong
      - --rc-web-gui-no-open-browser
      - --rc-web-gui-force-update
      - --rc-web-fetch-url=https://s3.yuudi.dev/rwa/embed/version.json
      - --config=/config/rclone/rclone.conf
      - --bwlimit
      - 10M:off
    deploy:
      resources:
        limits:
          memory: "7212105728"
    restart: unless-stopped