services:
  telegram-bot:
    image: ghcr.io/frozenfrog/telegram-bot:latest
    network_mode: host
    container_name: telegram-bot
    hostname: telegram-bot
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
    volumes:
      - type: bind
        source: "${BASEPATH}/${RClONE_CONFIG_PATH}/rclone.conf"
        target: /app/rclone.conf
    restart: unless-stopped
    labels:
      proxy.aliases: bot