[[stack]]
name = "home-automation"
tags = ["automation"]
[stack.config]
server = "HomeLab"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
linked_repo = "Komodo-Github"
run_directory = "stacks/HomeAutomation"
file_paths = [
  "homebridge.yaml",
  "shinobi.yaml"
]
env_file_path = "HomeAutomation.env"
additional_env_files = ["../../MainSystem/.env"]
environment = """
HOMEBRIDGE_CONFIG_PATH=homebridge-config
SHINOBI_CONFIG_PATH=shinobi-config
DB_HOST=192.168.1.3
DB_USER=majesticflame
DB_PASSWORD=
DB_DATABASE=ccio
SHINOBI_STORAGE_PATH=/mnt/Storage/IPC
"""

##

[[procedure]]
name = "Backup Core Database"
description = "Triggers the Core database backup at the scheduled time."
tags = ["system", "automation"]
config.schedule = "Every day at 23:00"

[[procedure.config.stage]]
name = "Stage 1"
enabled = true
executions = [
  { execution.type = "BackupCoreDatabase", execution.params = {}, enabled = true }
]

##

[[procedure]]
name = "Global Auto Update"
description = "Pulls and auto updates Stacks and Deployments using 'poll_for_updates' or 'auto_update'."
tags = ["system", "automation"]
config.schedule = "Every day at 23:00"

[[procedure.config.stage]]
name = "Stage 1"
enabled = true
executions = [
  { execution.type = "GlobalAutoUpdate", execution.params = {}, enabled = true }
]