[[stack]]
name = "home-automation"
tags = ["automation"]
[stack.config]
server = "HomeLab"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
linked_repo = "Komodo-Github"
run_directory = "stacks/HomeAutomation"
file_paths = [
  "homebridge.yaml",
  "shinobi.yaml"
]
env_file_path = "HomeAutomation.env"
additional_env_files = ["../../MainSystem/.env"]
environment = """
HOMEBRIDGE_CONFIG_PATH=homebridge-config
SHINOBI_CONFIG_PATH=shinobi-config
DB_HOST=192.168.1.3
DB_USER=majesticflame
DB_PASSWORD=
DB_DATABASE=ccio
SHINOBI_STORAGE_PATH=/mnt/Storage/IPC
"""