[[server]]
name = "HomeLab"
[server.config]
address = "https://host.docker.internal:8120"
region = "Vietnam"
enabled = true

##

[[stack]]
name = "adguard-home"
[stack.config]
server = "HomeLab"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
linked_repo = "Komodo-Github"
run_directory = "stacks/BackboneSystems"
file_paths = ["adguard_home.yaml"]
additional_env_files = ["../../MainSystem/.env"]
environment = """
APP_CONFIG_PATH=adguardhome-config
"""

##

[[stack]]
name = "karakeep"
[stack.config]
server = "HomeLab"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
linked_repo = "Komodo-Github"
run_directory = "stacks/Karakeep"
additional_env_files = ["../../MainSystem/.env"]
environment = """
MEILI_MASTER_KEY = [[ask-tick-any-gavel]]
NEXTAUTH_SECRET = [[storming-flapping-topped-maris]]
"""

##

[[stack]]
name = "template"
template = true
[stack.config]
server = "HomeLab"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
linked_repo = "Komodo-Github"
run_directory = "stacks"
additional_env_files = ["../../MainSystem/.env"]

##

[[stack]]
name = "vaultwarden"
[stack.config]
server = "HomeLab"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
linked_repo = "Komodo-Github"
run_directory = "stacks/Vaultwarden"
additional_env_files = ["../../MainSystem/.env"]
environment = """
APP_CONFIG_PATH=vaultwarden-config
"""

##

[[repo]]
name = "Komodo-Github"
[repo.config]
server = "HomeLab"
builder = "Local"
git_account = "FrozenFrog"
repo = "FrozenFrog/KomodoHomelab"

##

[[procedure]]
name = "Backup Core Database"
description = "Triggers the Core database backup at the scheduled time."
tags = ["system"]
config.schedule = "Every day at 23:00"

[[procedure.config.stage]]
name = "Stage 1"
enabled = true
executions = [
  { execution.type = "BackupCoreDatabase", execution.params = {}, enabled = true }
]

##

[[procedure]]
name = "Global Auto Update"
description = "Pulls and auto updates Stacks and Deployments using 'poll_for_updates' or 'auto_update'."
tags = ["system"]
config.schedule = "Every day at 23:00"

[[procedure.config.stage]]
name = "Stage 1"
enabled = true
executions = [
  { execution.type = "GlobalAutoUpdate", execution.params = {}, enabled = true }
]

##

[[alerter]]
name = "Alert"
[alerter.config]


##

[[builder]]
name = "Local"
[builder.config]
type = "Server"
params.server_id = "HomeLab"

##

[[resource_sync]]
name = "HomeLab-Github-Sync"
[resource_sync.config]
repo = "FrozenFrog/KomodoHomelab"
git_account = "FrozenFrog"
resource_path = ["MainSystem/komodo.toml"]
managed = true
delete = true
include_variables = true