services:
  agent:
    image: "ghcr.io/yusing/godoxy-agent:latest"
    container_name: godoxy-agent
    restart: always
    network_mode: host # do not change this
    environment:
      DOCKER_SOCKET: "/var/run/docker.sock"
      RUNTIME: "docker"
      AGENT_NAME: "OSCE!"
      AGENT_PORT: 8900
      AGENT_CA_CERT: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJsakNDQVR5Z0F3SUJBZ0lSQU13WFFML284MjIzMVNDQ2hBL0d1Z2N3Q2dZSUtvWkl6ajBFQXdJd0tERVAKTUEwR0ExVUVDaE1HUjI5RWIzaDVNUlV3RXdZRFZRUURFd3huYjJSdmVIa3VZV2RsYm5Rd0lCY05NalV4TVRJegpNVEkxTWpVeVdoZ1BNekF5TlRFeE1qTXhNalV5TlRKYU1DZ3hEekFOQmdOVkJBb1RCa2R2Ukc5NGVURVZNQk1HCkExVUVBeE1NWjI5a2IzaDVMbUZuWlc1ME1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRTlHTmsKMVN0cEs4YUxqUDNzenhwb0hncGN3V05xaEZMRnZFNUpseFkzOTZDYlZvS2gxTzMxdHlhc01JZTh2MFljY3BpMgo4bExxRERzTUdZQ2o4Ri9MUzZORk1FTXdEZ1lEVlIwUEFRSC9CQVFEQWdFR01CSUdBMVVkRXdFQi93UUlNQVlCCkFmOENBUUF3SFFZRFZSME9CQllFRkxzT3drd055UW8rekgrYWZ4NFZYL0MrV1pBUU1Bb0dDQ3FHU000OUJBTUMKQTBnQU1FVUNJUUNtMDRMdFFQbVgwaGdrdnE3bHp3TXRyTEpnVjlta2JlcnhSUkhsM0ZLVHd3SWdDcDBKQ1dNagpZbXZtVjNrSVlvWlBabEVjQkVyTEhzcWZRNEl0TVplYUE5az0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=;LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSU9sU0dCK1hoTjExSXNjMG9kSkltbHBDUFhCajNHVEk5UkwvY3hTeE9lYmVvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFOUdOazFTdHBLOGFMalAzc3p4cG9IZ3Bjd1dOcWhGTEZ2RTVKbHhZMzk2Q2JWb0toMU8zMQp0eWFzTUllOHYwWWNjcGkyOGxMcUREc01HWUNqOEYvTFN3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo="
      AGENT_SSL_CERT: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJvakNDQVVpZ0F3SUJBZ0lSQUswT2JRc1NINTlIV0VLdnRITWRKckV3Q2dZSUtvWkl6ajBFQXdJd0tERVAKTUEwR0ExVUVDaE1HUjI5RWIzaDVNUlV3RXdZRFZRUURFd3huYjJSdmVIa3VZV2RsYm5Rd0lCY05NalV4TVRJegpNVEkxTWpVeVdoZ1BNekF5TlRFeE1qTXhNalV5TlRKYU1Ea3hEekFOQmdOVkJBb1RCa2R2Ukc5NGVURVBNQTBHCkExVUVDeE1HVTJWeWRtVnlNUlV3RXdZRFZRUURFd3huYjJSdmVIa3VZV2RsYm5Rd1dUQVRCZ2NxaGtqT1BRSUIKQmdncWhrak9QUU1CQndOQ0FBU0E1NCszVVR1ZTBQS29OVjhPaWpaZHUyRXZDNDZ6eGE3V2JCam5UbXRURm12Vwo5eHVqK2lJZndOMXMxd3UwYU9Bamxrdy9Ud1JqcHNoMjFXYkZsVVdSbzBBd1BqQU9CZ05WSFE4QkFmOEVCQU1DCkI0QXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUhBd0V3RndZRFZSMFJCQkF3RG9JTVoyOWtiM2g1TG1GblpXNTAKTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSVFEdEUra0M1Q1gxdTNPN2xieTVHaWFEQ2ltekxNZzZnclpHL1ZXRgp4TEpMRndJZ0ZIWW1udFNqNXFuL3A0UGx5dnRhMDE0SyszWTdjNVNYSkRBN01lT05ndDg9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K;LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUhLdjM2cGhCQ2hBN1NIVG5hY0oyQkl5UUlqb2Y5R2xJSUt3UTdVNVBBOUVvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFZ09lUHQxRTdudER5cURWZkRvbzJYYnRoTHd1T3M4V3UxbXdZNTA1clV4WnIxdmNiby9vaQpIOERkYk5jTHRHamdJNVpNUDA4RVk2YklkdFZteFpWRmtRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo="
      # use agent as a docker socket proxy: [host]:port
      # set LISTEN_ADDR to enable (e.g. 127.0.0.1:2375)
      LISTEN_ADDR:
      POST: false
      ALLOW_RESTARTS: false
      ALLOW_START: false
      ALLOW_STOP: false
      AUTH: false
      BUILD: false
      COMMIT: false
      CONFIGS: false
      CONTAINERS: false
      DISTRIBUTION: false
      EVENTS: true
      EXEC: false
      GRPC: false
      IMAGES: false
      INFO: false
      NETWORKS: false
      NODES: false
      PING: true
      PLUGINS: false
      SECRETS: false
      SERVICES: false
      SESSION: false
      SWARM: false
      SYSTEM: false
      TASKS: false
      VERSION: true
      VOLUMES: false
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock
       - ${BASEPATH}/${APP_CONFIG_PATH}/agents:/app/data

    
